[theme] # You have to add this line

base = "dark"
primaryColor = '#7d33ff' # Y42 violet

# Not changing them for now
#backgroundColor = '#26282E' # Dark
#secondaryBackgroundColor = '#5B5E69' # Lighter grey